### ISSUE TITLE
ImportError: libmpi_cxx.so.40: cannot open shared object file

### ISSUE THREAD

**Issue by JimWang1991** [nict-wisdom/rannc#4]
@nict-wisdom Dear author, I installed rannc according to this command, and I am sure that I have installed OpenMPI v4.0.5 well.
````
conda create -n rannc python=3.8
conda activate rannc
conda install pytorch==1.8.0 cudatoolkit=10.2 -c pytorch
pip install pyrannc-0.5.0+cu102-cp38-cp38m-linux_x86_64.whl
````
and when run:
```
mpirun -np 2  python test.py
```
then this error appeared, how can I fix it?
````
mpirun -np 2  python test.py
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    import pyrannc
  File "/root/anaconda3/envs/rannc/lib/python3.8/site-packages/pyrannc/__init__.py", line 12, in <module>
    from . import _pyrannc
ImportError: libmpi_cxx.so.40: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    import pyrannc
  File "/root/anaconda3/envs/rannc/lib/python3.8/site-packages/pyrannc/__init__.py", line 12, in <module>
    from . import _pyrannc
ImportError: libmpi_cxx.so.40: cannot open shared object file: No such file or directory

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   EXIT CODE: 1
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
````
the test.py :
```
import torch
import torch.nn as nn
import torch.optim as optim
import pyrannc
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(3, 2, bias=False)
        self.fc2 = nn.Linear(2, 3, bias=False)
    def forward(self, x):
        x = self.fc1(x)
        x = self.fc2(x)
        return x
model = Net()
model.to(torch.device("cuda"))
opt = optim.SGD(model.parameters(), lr=0.01)
model = pyrannc.RaNNCModule(model, opt)
x = torch.randn(64, 3, requires_grad=True).to(torch.device("cuda"))
out = model(x)
target = torch.randn_like(out)
out.backward(target)
opt.step()
```

**Comment by nict-wisdom** [comment]
As this message suggests, `LD_LIBRARY_PATH` must include a directory that contains `libmpi_cxx.so.40`.

```
ImportError: libmpi_cxx.so.40: cannot open shared object file: No such file or directory
```

To install `libmpi_cxx.so.40`, you need to enable c++ option when you run  `./configure` for MPI.
See the [Dockerfile](https://github.com/nict-wisdom/rannc/blob/ee3133128e8f923d7d9386163624cf50f7d46fac/docker/ubuntu/base/Dockerfile#L50) to generate pip packages for details.

 [Makefiles to generate packages](https://github.com/nict-wisdom/rannc/blob/ee3133128e8f923d7d9386163624cf50f7d46fac/docker/ubuntu/Makefile) also create docker/singularity containers for RaNNC.
Try the containers if you can run docker or singularity.

**Comment by JimWang1991** [comment]
@nict-wisdom Thank you very much for your advice. and it works when I re-configure and install openMPI
